package com.steve.recyclerviewdatabinding

import androidx.lifecycle.ViewModel

class MainViewModel: ViewModel() {
    var mdata:ArrayList<RecycleData> =ArrayList()

    init {
        mdata.add(RecycleData("steve","stevechacha@gmail.com","married"))
        mdata.add(RecycleData("steve1","stevecacha4@gmail.com","divoced"))
        mdata.add(RecycleData("stev1e","stevechaha4@gmail.com","Single"))
        mdata.add(RecycleData("stev2e","steechcha4@gmail.com","single"))
        mdata.add(RecycleData("steve","stevechacha@gmail.com","married"))
        mdata.add(RecycleData("steve1","stevecacha4@gmail.com","divoced"))
        mdata.add(RecycleData("stev1e","stevechaha4@gmail.com","Single"))
        mdata.add(RecycleData("steve","stevechacha@gmail.com","married"))
        mdata.add(RecycleData("steve1","stevecacha4@gmail.com","divoced"))
        mdata.add(RecycleData("stev1e","stevechaha4@gmail.com","Single"))
        mdata.add(RecycleData("stev2e","steechcha4@gmail.com","single"))
        mdata.add(RecycleData("steve","stevechacha@gmail.com","married"))
        mdata.add(RecycleData("steve1","stevecacha4@gmail.com","divoced"))
        mdata.add(RecycleData("stev1e","stevechaha4@gmail.com","Single"))
        mdata.add(RecycleData("stev2e","steechcha4@gmail.com","single"))
        mdata.add(RecycleData("steve","stevechacha@gmail.com","married"))
        mdata.add(RecycleData("steve1","stevecacha4@gmail.com","divoced"))
        mdata.add(RecycleData("stev1e","stevechaha4@gmail.com","Single"))
        mdata.add(RecycleData("stev2e","steechcha4@gmail.com","single"))
        mdata.add(RecycleData("steve","stevechacha@gmail.com","married"))
        mdata.add(RecycleData("steve1","stevecacha4@gmail.com","divoced"))
        mdata.add(RecycleData("stev1e","stevechaha4@gmail.com","Single"))
        mdata.add(RecycleData("steve","stevechacha@gmail.com","married"))
        mdata.add(RecycleData("steve1","stevecacha4@gmail.com","divoced"))
        mdata.add(RecycleData("stev1e","stevechaha4@gmail.com","Single"))
        mdata.add(RecycleData("stev2e","steechcha4@gmail.com","single"))
        mdata.add(RecycleData("steve","stevechacha@gmail.com","married"))
        mdata.add(RecycleData("steve1","stevecacha4@gmail.com","divoced"))
        mdata.add(RecycleData("stev1e","stevechaha4@gmail.com","Single"))
        mdata.add(RecycleData("stev2e","steechcha4@gmail.com","single"))
        mdata.add(RecycleData("steve","stevechacha@gmail.com","married"))
        mdata.add(RecycleData("steve1","stevecacha4@gmail.com","divoced"))
        mdata.add(RecycleData("stev1e","stevechaha4@gmail.com","Single"))
        mdata.add(RecycleData("stev2e","steechcha4@gmail.com","single"))
        mdata.add(RecycleData("steve","stevechacha@gmail.com","married"))
        mdata.add(RecycleData("steve1","stevecacha4@gmail.com","divoced"))
        mdata.add(RecycleData("stev1e","stevechaha4@gmail.com","Single"))
        mdata.add(RecycleData("steve","stevechacha@gmail.com","married"))
        mdata.add(RecycleData("steve1","stevecacha4@gmail.com","divoced"))
        mdata.add(RecycleData("stev1e","stevechaha4@gmail.com","Single"))
        mdata.add(RecycleData("stev2e","steechcha4@gmail.com","single"))
        mdata.add(RecycleData("steve","stevechacha@gmail.com","married"))
        mdata.add(RecycleData("steve1","stevecacha4@gmail.com","divoced"))
        mdata.add(RecycleData("stev1e","stevechaha4@gmail.com","Single"))
        mdata.add(RecycleData("stev2e","steechcha4@gmail.com","single"))
        mdata.add(RecycleData("steve","stevechacha@gmail.com","married"))
        mdata.add(RecycleData("steve1","stevecacha4@gmail.com","divoced"))
        mdata.add(RecycleData("stev1e","stevechaha4@gmail.com","Single"))
        mdata.add(RecycleData("stev2e","steechcha4@gmail.com","single"))
        mdata.add(RecycleData("steve","stevechacha@gmail.com","married"))
        mdata.add(RecycleData("steve1","stevecacha4@gmail.com","divoced"))
        mdata.add(RecycleData("stev1e","stevechaha4@gmail.com","Single"))
        mdata.add(RecycleData("steve","stevechacha@gmail.com","married"))
        mdata.add(RecycleData("steve1","stevecacha4@gmail.com","divoced"))
        mdata.add(RecycleData("stev1e","stevechaha4@gmail.com","Single"))
        mdata.add(RecycleData("stev2e","steechcha4@gmail.com","single"))
        mdata.add(RecycleData("steve","stevechacha@gmail.com","married"))
        mdata.add(RecycleData("steve1","stevecacha4@gmail.com","divoced"))
        mdata.add(RecycleData("stev1e","stevechaha4@gmail.com","Single"))
        mdata.add(RecycleData("stev2e","steechcha4@gmail.com","single"))
        mdata.add(RecycleData("steve","stevechacha@gmail.com","married"))
        mdata.add(RecycleData("steve1","stevecacha4@gmail.com","divoced"))
        mdata.add(RecycleData("stev1e","stevechaha4@gmail.com","Single"))
        mdata.add(RecycleData("stev2e","steechcha4@gmail.com","single"))
        mdata.add(RecycleData("steve","stevechacha@gmail.com","married"))
        mdata.add(RecycleData("steve1","stevecacha4@gmail.com","divoced"))
        mdata.add(RecycleData("stev1e","stevechaha4@gmail.com","Single"))
        mdata.add(RecycleData("steve","stevechacha@gmail.com","married"))
        mdata.add(RecycleData("steve1","stevecacha4@gmail.com","divoced"))
        mdata.add(RecycleData("stev1e","stevechaha4@gmail.com","Single"))
        mdata.add(RecycleData("stev2e","steechcha4@gmail.com","single"))
        mdata.add(RecycleData("steve","stevechacha@gmail.com","married"))
        mdata.add(RecycleData("steve1","stevecacha4@gmail.com","divoced"))
        mdata.add(RecycleData("stev1e","stevechaha4@gmail.com","Single"))
        mdata.add(RecycleData("stev2e","steechcha4@gmail.com","single"))
        mdata.add(RecycleData("steve","stevechacha@gmail.com","married"))
        mdata.add(RecycleData("steve1","stevecacha4@gmail.com","divoced"))
        mdata.add(RecycleData("stev1e","stevechaha4@gmail.com","Single"))
        mdata.add(RecycleData("stev2e","steechcha4@gmail.com","single"))
        mdata.add(RecycleData("steve","stevechacha@gmail.com","married"))
        mdata.add(RecycleData("steve1","stevecacha4@gmail.com","divoced"))
        mdata.add(RecycleData("stev1e","stevechaha4@gmail.com","Single"))
        mdata.add(RecycleData("steve","stevechacha@gmail.com","married"))
        mdata.add(RecycleData("steve1","stevecacha4@gmail.com","divoced"))
        mdata.add(RecycleData("stev1e","stevechaha4@gmail.com","Single"))
        mdata.add(RecycleData("stev2e","steechcha4@gmail.com","single"))
        mdata.add(RecycleData("steve","stevechacha@gmail.com","married"))
        mdata.add(RecycleData("steve1","stevecacha4@gmail.com","divoced"))
        mdata.add(RecycleData("stev1e","stevechaha4@gmail.com","Single"))
        mdata.add(RecycleData("stev2e","steechcha4@gmail.com","single"))
        mdata.add(RecycleData("steve","stevechacha@gmail.com","married"))
        mdata.add(RecycleData("steve1","stevecacha4@gmail.com","divoced"))
        mdata.add(RecycleData("stev1e","stevechaha4@gmail.com","Single"))
        mdata.add(RecycleData("stev2e","steechcha4@gmail.com","single"))
        mdata.add(RecycleData("steve","stevechacha@gmail.com","married"))
        mdata.add(RecycleData("steve1","stevecacha4@gmail.com","divoced"))
        mdata.add(RecycleData("stev1e","stevechaha4@gmail.com","Single"))
        mdata.add(RecycleData("steve","stevechacha@gmail.com","married"))
        mdata.add(RecycleData("steve1","stevecacha4@gmail.com","divoced"))
        mdata.add(RecycleData("stev1e","stevechaha4@gmail.com","Single"))
        mdata.add(RecycleData("stev2e","steechcha4@gmail.com","single"))
        mdata.add(RecycleData("steve","stevechacha@gmail.com","married"))
        mdata.add(RecycleData("steve1","stevecacha4@gmail.com","divoced"))
        mdata.add(RecycleData("stev1e","stevechaha4@gmail.com","Single"))
        mdata.add(RecycleData("stev2e","steechcha4@gmail.com","single"))
        mdata.add(RecycleData("steve","stevechacha@gmail.com","married"))
        mdata.add(RecycleData("steve1","stevecacha4@gmail.com","divoced"))
        mdata.add(RecycleData("stev1e","stevechaha4@gmail.com","Single"))
        mdata.add(RecycleData("stev2e","steechcha4@gmail.com","single"))
        mdata.add(RecycleData("steve","stevechacha@gmail.com","married"))
        mdata.add(RecycleData("steve1","stevecacha4@gmail.com","divoced"))
        mdata.add(RecycleData("stev1e","stevechaha4@gmail.com","Single"))
        mdata.add(RecycleData("steve","stevechacha@gmail.com","married"))
        mdata.add(RecycleData("steve1","stevecacha4@gmail.com","divoced"))
        mdata.add(RecycleData("stev1e","stevechaha4@gmail.com","Single"))
        mdata.add(RecycleData("stev2e","steechcha4@gmail.com","single"))
        mdata.add(RecycleData("steve","stevechacha@gmail.com","married"))
        mdata.add(RecycleData("steve1","stevecacha4@gmail.com","divoced"))
        mdata.add(RecycleData("stev1e","stevechaha4@gmail.com","Single"))
        mdata.add(RecycleData("stev2e","steechcha4@gmail.com","single"))
    }
    var adapter=RecyclerAdapter(R.layout.item_row,mdata,this)

    fun setAdapter():RecyclerAdapter{
        return adapter
    }

    fun onClick(position:Int){

    }
    fun setStatus(position:Int):String {
     return mdata.get(position).status
    }
    fun setTitle(position:Int):String{
        return mdata.get(position).name
    }

    fun setEmail(position:Int):String{
   return mdata.get(position).email
    }


}